[package]
name = "division_shader_compiler_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1.50"

[dev-dependencies]
walkdir = "2.3.3"

[dependencies]
